### ISSUE TITLE
Change "Done" to send

### ISSUE THREAD

**Issue by mackelito** [mattermost/ios#26]
When writing a message you have a "done" button next to the input field.
Clicking that closes the keyboard.

I would rather see that it sends the message (stolen from other apps such as message, slack, whatsapp and many more)

**Comment by lfbrock** [comment]
Hi @mackelito, we were actually thinking of changing the enter button to create a new line in a message:
https://mattermost.atlassian.net/browse/PLT-2331

Some other users wanted to be able to create new lines on mobile, and suggested we change "enter" to create a new line and then the send icon will send the message. 

What are your thoughts on this?

**Comment by mackelito** [comment]
I think that is a great idea but I believe we are talking about different buttons :)

- return/enter, should create a new line
- Done should be changed into Send and submit the text.

:)

**Comment by asaadmahmoodspin** [comment]
Hey @mackelito I would think that you're probably talking about the default keyboard toolbar that appears.
Note that most of the apps don't actually have that toolbar and it doesn't make sense since it allows you to go back and forth between different inputs and tap done when you're entering data.

The send button you see in most of those apps is actually part of our UI aswell, We just need to hide that default toolbar so it does not confuse users. I'll bring that up in the UX meeting.

![asd](https://cloud.githubusercontent.com/assets/11034289/15033321/de8e769a-1282-11e6-9e58-55d34a469f1d.jpg)

**Comment by lfbrock** [comment]
Hi @mackelito, would you be able to open a [feature request](http://www.mattermost.org/feature-requests/) on this instead? 

We discussed and agree your suggestion makes sense, but I don't think we can add this until we make the apps fully native.

**Comment by mackelito** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/13752930-remove-the-toolbar-when-sending-message-the-done

**Comment by mackelito** [comment]
For reference:
https://mattermost.uservoice.com/forums/306457-general/suggestions/10975914-ios-keyboard-improvements
https://github.com/mattermost/platform/issues/1607
